kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: reireias/argocd
      tags: linux-amd64-${DRONE_TAG}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: reireias/argocd
      tags: linux-arm64-${DRONE_TAG}
      build_args:
        - BUILD_ALL_CLIS="false"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: reireias/argocd
      tags: linux-arm-${DRONE_TAG}
      build_args:
        - BUILD_ALL_CLIS="false"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - tag

---
kind: pipeline
type: docker
name: manifest

steps:
  - name: publish
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: reireias/argocd:${DRONE_TAG}
      template: reireias/argocd:OS-ARCH-${DRONE_TAG}
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64

trigger:
  event:
    - tag

depends_on:
  - linux-arm64
  - linux-arm
  - linux-amd64
