name: main

on:
  push:
    branches:
      - feature/arm

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup docker for arm
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: push image
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          make image
        env:
          IMAGE_NAMESPACE: reireias
          DOCKER_PUSH: true
          GOARCH: arm
          GOARM: 7
